import React from 'react'
import styles from './Navbar.module.css'
import Link from 'next/link'
import Head from 'next/head'
import Script from 'next/script'
import {useRouter} from 'next/router';
const Navbar  = () => {
  const router = useRouter()
  return (
    <div className={styles.Navbar}>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="https://www.google-analytics.com/analytics.js" strategy="lazyOnload" />
      </Head>
      <>
        {/* <h2>pathname:- {router.pathname}</h2>
        <h2>asPath:- {router.asPath}</h2>
       */}
      </>
      <ul>
      
    <li><Link href="/" >
          <a className={router.pathname === "/" ? styles.active:""} >Home</a>
        </Link>
        </li>
    <li>
      <Link href="/about" >
          <a  className={router.pathname === "/about"  ? styles.active:""}>About</a>
        </Link>
     </li>
    <li>
      <Link href="/blog/myblog" >
          <a className={router.pathname === "/blog/myblog" ? styles.active:""} >Blog</a>
        </Link>
       </li>
    <li>
    <Link href="/blog/shrushti" >
          <a className={router.pathname === "/blog/[blogId]" ? styles.active:""} >Dynamic blog</a>
        </Link>
       </li>
  </ul>
  </div>
  )
}
export default Navbar;